services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: risk
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST_AUTH_METHOD: trust

connect:
  image: postgres
  script:
    # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy

build:
  tags:
     - testing,deployment
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - testing,deployment
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage

deploy:
  tags:
     - testing,deployment
  stage: deploy
  script: ./scripts/redeploy.sh
  

pages:
 stage: coverage
 tags:
     - testing,deployment
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public

