before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage

   
build:
  tags:
     - ECE 651 group4 CI
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ECE 651 group4 CI
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ECE 651 group4 CI
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public
